spring:
  datasource:
    url: jdbc:postgresql://mypostgres:5432/postgres
    username: postgres
    password: cms@spring
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    generate-ddl: true


kafka:
  bootstrapAddress: kafka:9093
  producer:
    value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    
message:
  topic:
    name: orderItem      
    
partitioned:
  topic:
    name: orderItem      
    
filtered:
  topic:
    name: orderItem      
    
greeting:
  topic:
    name: test